# Based off GitHub defaults
# https://help.github.com/articles/configuring-jekyll/#defaults-you-can-change
# github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-paginate

# GitHub sets these--and they cannot be changed there
# https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
